var annotated =
[
    [ "gurls::BadConfidenceCreation", "d3/d2a/classgurls_1_1_bad_confidence_creation.html", "d3/d2a/classgurls_1_1_bad_confidence_creation" ],
    [ "gurls::BadKernelCreation", "da/d16/classgurls_1_1_bad_kernel_creation.html", "da/d16/classgurls_1_1_bad_kernel_creation" ],
    [ "gurls::BadNormCreation", "dc/d93/classgurls_1_1_bad_norm_creation.html", "dc/d93/classgurls_1_1_bad_norm_creation" ],
    [ "gurls::BadOptimizerCreation", "d1/d0d/classgurls_1_1_bad_optimizer_creation.html", "d1/d0d/classgurls_1_1_bad_optimizer_creation" ],
    [ "gurls::BadParamSelectionCreation", "d9/dc4/classgurls_1_1_bad_param_selection_creation.html", "d9/dc4/classgurls_1_1_bad_param_selection_creation" ],
    [ "gurls::BadPerformanceCreation", "dd/ddf/classgurls_1_1_bad_performance_creation.html", "dd/ddf/classgurls_1_1_bad_performance_creation" ],
    [ "gurls::BadPredictionCreation", "d4/dd1/classgurls_1_1_bad_prediction_creation.html", "d4/dd1/classgurls_1_1_bad_prediction_creation" ],
    [ "gurls::BadPredKernelCreation", "d8/d5f/classgurls_1_1_bad_pred_kernel_creation.html", "d8/d5f/classgurls_1_1_bad_pred_kernel_creation" ],
    [ "gurls::BadSplitCreation", "d7/d5c/classgurls_1_1_bad_split_creation.html", "d7/d5c/classgurls_1_1_bad_split_creation" ],
    [ "gurls::BaseArray< T >", "d9/d8b/classgurls_1_1_base_array.html", "d9/d8b/classgurls_1_1_base_array" ],
    [ "gurls::BlasUtils", "da/dfd/classgurls_1_1_blas_utils.html", "da/dfd/classgurls_1_1_blas_utils" ],
    [ "gurls::ConfBoltzman< T >", "dd/d88/classgurls_1_1_conf_boltzman.html", "dd/d88/classgurls_1_1_conf_boltzman" ],
    [ "gurls::ConfBoltzmanGap< T >", "d0/d77/classgurls_1_1_conf_boltzman_gap.html", "d0/d77/classgurls_1_1_conf_boltzman_gap" ],
    [ "gurls::ConfGap< T >", "d8/dbc/classgurls_1_1_conf_gap.html", "d8/dbc/classgurls_1_1_conf_gap" ],
    [ "gurls::Confidence< T >", "da/d7d/classgurls_1_1_confidence.html", "da/d7d/classgurls_1_1_confidence" ],
    [ "gurls::ConfMaxScore< T >", "de/ded/classgurls_1_1_conf_max_score.html", "de/ded/classgurls_1_1_conf_max_score" ],
    [ "gurls::Functor", "d5/dc9/classgurls_1_1_functor.html", "d5/dc9/classgurls_1_1_functor" ],
    [ "gurls::gException", "d1/d29/classgurls_1_1g_exception.html", "d1/d29/classgurls_1_1g_exception" ],
    [ "gurls::gMat2D< T >", "d1/d9e/classgurls_1_1g_mat2_d.html", "d1/d9e/classgurls_1_1g_mat2_d" ],
    [ "gurls::GPRWrapper< T >", "d1/d6d/classgurls_1_1_g_p_r_wrapper.html", "d1/d6d/classgurls_1_1_g_p_r_wrapper" ],
    [ "gurls::GURLS", "d4/dbe/classgurls_1_1_g_u_r_l_s.html", "d4/dbe/classgurls_1_1_g_u_r_l_s" ],
    [ "gurls::GurlsOption", "d5/dcc/classgurls_1_1_gurls_option.html", "d5/dcc/classgurls_1_1_gurls_option" ],
    [ "gurls::GurlsOptionsList", "dc/d34/classgurls_1_1_gurls_options_list.html", "dc/d34/classgurls_1_1_gurls_options_list" ],
    [ "gurls::GurlsWrapper< T >", "d5/d55/classgurls_1_1_gurls_wrapper.html", "d5/d55/classgurls_1_1_gurls_wrapper" ],
    [ "gurls::gVec< T >", "df/d32/classgurls_1_1g_vec.html", "df/d32/classgurls_1_1g_vec" ],
    [ "gurls::ICholWrapper< T >", "df/d35/classgurls_1_1_i_chol_wrapper.html", "df/d35/classgurls_1_1_i_chol_wrapper" ],
    [ "gurls::Kernel< T >", "dc/d0c/classgurls_1_1_kernel.html", "dc/d0c/classgurls_1_1_kernel" ],
    [ "gurls::KernelChisquared< T >", "dc/d82/classgurls_1_1_kernel_chisquared.html", "dc/d82/classgurls_1_1_kernel_chisquared" ],
    [ "gurls::KernelLinear< T >", "d8/d84/classgurls_1_1_kernel_linear.html", "d8/d84/classgurls_1_1_kernel_linear" ],
    [ "gurls::KernelRBF< T >", "d0/d97/classgurls_1_1_kernel_r_b_f.html", "d0/d97/classgurls_1_1_kernel_r_b_f" ],
    [ "gurls::KernelRLSWrapper< T >", "da/d5c/classgurls_1_1_kernel_r_l_s_wrapper.html", "da/d5c/classgurls_1_1_kernel_r_l_s_wrapper" ],
    [ "gurls::KernelWrapper< T >", "d1/db4/classgurls_1_1_kernel_wrapper.html", "d1/db4/classgurls_1_1_kernel_wrapper" ],
    [ "gurls::LtCompare< T >", "d0/db4/classgurls_1_1_lt_compare.html", "d0/db4/classgurls_1_1_lt_compare" ],
    [ "gurls::Max", "dd/de1/classgurls_1_1_max.html", "dd/de1/classgurls_1_1_max" ],
    [ "gurls::Mean", "d2/de4/classgurls_1_1_mean.html", "d2/de4/classgurls_1_1_mean" ],
    [ "gurls::Median", "d2/dc0/classgurls_1_1_median.html", "d2/dc0/classgurls_1_1_median" ],
    [ "gurls::Min", "d4/d6c/classgurls_1_1_min.html", "d4/d6c/classgurls_1_1_min" ],
    [ "gurls::Norm< T >", "d9/d56/classgurls_1_1_norm.html", "d9/d56/classgurls_1_1_norm" ],
    [ "gurls::NormL2< T >", "db/d42/classgurls_1_1_norm_l2.html", "db/d42/classgurls_1_1_norm_l2" ],
    [ "gurls::NormTestZScore< T >", "db/d98/classgurls_1_1_norm_test_z_score.html", "db/d98/classgurls_1_1_norm_test_z_score" ],
    [ "gurls::NormZScore< T >", "d5/dec/classgurls_1_1_norm_z_score.html", "d5/dec/classgurls_1_1_norm_z_score" ],
    [ "gurls::NystromWrapper< T >", "d2/d25/classgurls_1_1_nystrom_wrapper.html", "d2/d25/classgurls_1_1_nystrom_wrapper" ],
    [ "gurls::OptArray", "da/d90/classgurls_1_1_opt_array.html", "da/d90/classgurls_1_1_opt_array" ],
    [ "gurls::OptFunction", "d8/d4b/classgurls_1_1_opt_function.html", "d8/d4b/classgurls_1_1_opt_function" ],
    [ "gurls::Optimizer< T >", "d6/ddf/classgurls_1_1_optimizer.html", "d6/ddf/classgurls_1_1_optimizer" ],
    [ "gurls::OptMatrix< Matrix >", "de/d63/classgurls_1_1_opt_matrix.html", "de/d63/classgurls_1_1_opt_matrix" ],
    [ "gurls::OptMatrixBase", "d3/dfe/classgurls_1_1_opt_matrix_base.html", "d3/dfe/classgurls_1_1_opt_matrix_base" ],
    [ "gurls::OptNumber", "d9/d58/classgurls_1_1_opt_number.html", "d9/d58/classgurls_1_1_opt_number" ],
    [ "gurls::OptNumberList", "df/dda/classgurls_1_1_opt_number_list.html", "df/dda/classgurls_1_1_opt_number_list" ],
    [ "gurls::OptProcess", "db/d52/classgurls_1_1_opt_process.html", "db/d52/classgurls_1_1_opt_process" ],
    [ "gurls::OptString", "d0/d48/classgurls_1_1_opt_string.html", "d0/d48/classgurls_1_1_opt_string" ],
    [ "gurls::OptStringList", "d7/da3/classgurls_1_1_opt_string_list.html", "d7/da3/classgurls_1_1_opt_string_list" ],
    [ "gurls::OptTaskSequence", "dc/d25/classgurls_1_1_opt_task_sequence.html", "dc/d25/classgurls_1_1_opt_task_sequence" ],
    [ "gurls::ParamSelCalibrateSGD< T >", "d6/dae/classgurls_1_1_param_sel_calibrate_s_g_d.html", "d6/dae/classgurls_1_1_param_sel_calibrate_s_g_d" ],
    [ "gurls::ParamSelection< T >", "d8/d85/classgurls_1_1_param_selection.html", "d8/d85/classgurls_1_1_param_selection" ],
    [ "gurls::ParamSelFixLambda< T >", "dd/de6/classgurls_1_1_param_sel_fix_lambda.html", "dd/de6/classgurls_1_1_param_sel_fix_lambda" ],
    [ "gurls::ParamSelFixSigLam< T >", "dd/d8a/classgurls_1_1_param_sel_fix_sig_lam.html", "dd/d8a/classgurls_1_1_param_sel_fix_sig_lam" ],
    [ "gurls::ParamSelHoDual< T >", "de/dc2/classgurls_1_1_param_sel_ho_dual.html", "de/dc2/classgurls_1_1_param_sel_ho_dual" ],
    [ "gurls::ParamSelHoDualr< T >", "d0/d9b/classgurls_1_1_param_sel_ho_dualr.html", "d0/d9b/classgurls_1_1_param_sel_ho_dualr" ],
    [ "gurls::ParamSelHoGPRegr< T >", "d6/d89/classgurls_1_1_param_sel_ho_g_p_regr.html", "d6/d89/classgurls_1_1_param_sel_ho_g_p_regr" ],
    [ "gurls::ParamSelHoPrimal< T >", "da/d0c/classgurls_1_1_param_sel_ho_primal.html", "da/d0c/classgurls_1_1_param_sel_ho_primal" ],
    [ "gurls::ParamSelHoPrimalr< T >", "db/dc8/classgurls_1_1_param_sel_ho_primalr.html", "db/dc8/classgurls_1_1_param_sel_ho_primalr" ],
    [ "gurls::ParamSelLoocvDual< T >", "dd/de0/classgurls_1_1_param_sel_loocv_dual.html", "dd/de0/classgurls_1_1_param_sel_loocv_dual" ],
    [ "gurls::ParamSelLoocvPrimal< T >", "d3/d1d/classgurls_1_1_param_sel_loocv_primal.html", "d3/d1d/classgurls_1_1_param_sel_loocv_primal" ],
    [ "gurls::ParamSelLooGPRegr< T >", "da/d9c/classgurls_1_1_param_sel_loo_g_p_regr.html", "da/d9c/classgurls_1_1_param_sel_loo_g_p_regr" ],
    [ "gurls::ParamSelSiglam< T >", "d6/d3a/classgurls_1_1_param_sel_siglam.html", "d6/d3a/classgurls_1_1_param_sel_siglam" ],
    [ "gurls::ParamSelSiglamHo< T >", "dc/de3/classgurls_1_1_param_sel_siglam_ho.html", "dc/de3/classgurls_1_1_param_sel_siglam_ho" ],
    [ "gurls::ParamSelSiglamHoGPRegr< T >", "d1/de1/classgurls_1_1_param_sel_siglam_ho_g_p_regr.html", "d1/de1/classgurls_1_1_param_sel_siglam_ho_g_p_regr" ],
    [ "gurls::ParamSelSiglamLooGPRegr< T >", "d0/d75/classgurls_1_1_param_sel_siglam_loo_g_p_regr.html", "d0/d75/classgurls_1_1_param_sel_siglam_loo_g_p_regr" ],
    [ "gurls::PerfMacroAvg< T >", "d8/dc8/classgurls_1_1_perf_macro_avg.html", "d8/dc8/classgurls_1_1_perf_macro_avg" ],
    [ "gurls::Performance< T >", "d5/dac/classgurls_1_1_performance.html", "d5/dac/classgurls_1_1_performance" ],
    [ "gurls::PerfPrecRec< T >", "d6/dbc/classgurls_1_1_perf_prec_rec.html", "d6/dbc/classgurls_1_1_perf_prec_rec" ],
    [ "gurls::PerfRmse< T >", "d8/dc3/classgurls_1_1_perf_rmse.html", "d8/dc3/classgurls_1_1_perf_rmse" ],
    [ "gurls::PredDual< T >", "d7/dcd/classgurls_1_1_pred_dual.html", "d7/dcd/classgurls_1_1_pred_dual" ],
    [ "gurls::PredGPRegr< T >", "da/d9e/classgurls_1_1_pred_g_p_regr.html", "da/d9e/classgurls_1_1_pred_g_p_regr" ],
    [ "gurls::Prediction< T >", "d7/d57/classgurls_1_1_prediction.html", "d7/d57/classgurls_1_1_prediction" ],
    [ "gurls::PredKernel< T >", "d1/d99/classgurls_1_1_pred_kernel.html", "d1/d99/classgurls_1_1_pred_kernel" ],
    [ "gurls::PredKernelTrainTest< T >", "d3/dd7/classgurls_1_1_pred_kernel_train_test.html", "d3/dd7/classgurls_1_1_pred_kernel_train_test" ],
    [ "gurls::PredPrimal< T >", "d8/d06/classgurls_1_1_pred_primal.html", "d8/d06/classgurls_1_1_pred_primal" ],
    [ "gurls::PredRandFeats< T >", "d7/da4/classgurls_1_1_pred_rand_feats.html", "d7/da4/classgurls_1_1_pred_rand_feats" ],
    [ "gurls::RandomFeaturesWrapper< T >", "db/de1/classgurls_1_1_random_features_wrapper.html", "db/de1/classgurls_1_1_random_features_wrapper" ],
    [ "gurls::RecursiveRLSWrapper< T >", "d5/dc3/classgurls_1_1_recursive_r_l_s_wrapper.html", "d5/dc3/classgurls_1_1_recursive_r_l_s_wrapper" ],
    [ "gurls::RLSAuto< T >", "d5/d00/classgurls_1_1_r_l_s_auto.html", "d5/d00/classgurls_1_1_r_l_s_auto" ],
    [ "gurls::RLSDual< T >", "d3/d15/classgurls_1_1_r_l_s_dual.html", "d3/d15/classgurls_1_1_r_l_s_dual" ],
    [ "gurls::RLSDualr< T >", "d9/d3f/classgurls_1_1_r_l_s_dualr.html", "d9/d3f/classgurls_1_1_r_l_s_dualr" ],
    [ "gurls::RLSGPRegr< T >", "d4/db3/classgurls_1_1_r_l_s_g_p_regr.html", "d4/db3/classgurls_1_1_r_l_s_g_p_regr" ],
    [ "gurls::RLSPegasos< T >", "df/d7d/classgurls_1_1_r_l_s_pegasos.html", "df/d7d/classgurls_1_1_r_l_s_pegasos" ],
    [ "gurls::RLSPrimal< T >", "d6/dbd/classgurls_1_1_r_l_s_primal.html", "d6/dbd/classgurls_1_1_r_l_s_primal" ],
    [ "gurls::RLSPrimalr< T >", "d0/df5/classgurls_1_1_r_l_s_primalr.html", "d0/df5/classgurls_1_1_r_l_s_primalr" ],
    [ "gurls::RLSPrimalRecInit< T >", "d2/d8f/classgurls_1_1_r_l_s_primal_rec_init.html", "d2/d8f/classgurls_1_1_r_l_s_primal_rec_init" ],
    [ "gurls::RLSPrimalRecUpdate< T >", "d6/dad/classgurls_1_1_r_l_s_primal_rec_update.html", "d6/dad/classgurls_1_1_r_l_s_primal_rec_update" ],
    [ "gurls::RLSRandFeats< T >", "d4/dd6/classgurls_1_1_r_l_s_rand_feats.html", "d4/dd6/classgurls_1_1_r_l_s_rand_feats" ],
    [ "gurls::RLSWrapper< T >", "d0/d09/classgurls_1_1_r_l_s_wrapper.html", "d0/d09/classgurls_1_1_r_l_s_wrapper" ],
    [ "gurls::Split< T >", "d7/d41/classgurls_1_1_split.html", "d7/d41/classgurls_1_1_split" ],
    [ "gurls::SplitHo< T >", "da/d75/classgurls_1_1_split_ho.html", "da/d75/classgurls_1_1_split_ho" ]
];