var searchData=
[
  ['paramselcalibratesgd',['ParamSelCalibrateSGD',['../d6/dae/classgurls_1_1_param_sel_calibrate_s_g_d.html',1,'gurls']]],
  ['paramselection',['ParamSelection',['../d8/d85/classgurls_1_1_param_selection.html',1,'gurls']]],
  ['paramselfixlambda',['ParamSelFixLambda',['../dd/de6/classgurls_1_1_param_sel_fix_lambda.html',1,'gurls']]],
  ['paramselfixsiglam',['ParamSelFixSigLam',['../dd/d8a/classgurls_1_1_param_sel_fix_sig_lam.html',1,'gurls']]],
  ['paramselhodual',['ParamSelHoDual',['../de/dc2/classgurls_1_1_param_sel_ho_dual.html',1,'gurls']]],
  ['paramselhodualr',['ParamSelHoDualr',['../d0/d9b/classgurls_1_1_param_sel_ho_dualr.html',1,'gurls']]],
  ['paramselhogpregr',['ParamSelHoGPRegr',['../d6/d89/classgurls_1_1_param_sel_ho_g_p_regr.html',1,'gurls']]],
  ['paramselhoprimal',['ParamSelHoPrimal',['../da/d0c/classgurls_1_1_param_sel_ho_primal.html',1,'gurls']]],
  ['paramselhoprimalr',['ParamSelHoPrimalr',['../db/dc8/classgurls_1_1_param_sel_ho_primalr.html',1,'gurls']]],
  ['paramselloocvdual',['ParamSelLoocvDual',['../dd/de0/classgurls_1_1_param_sel_loocv_dual.html',1,'gurls']]],
  ['paramselloocvprimal',['ParamSelLoocvPrimal',['../d3/d1d/classgurls_1_1_param_sel_loocv_primal.html',1,'gurls']]],
  ['paramselloogpregr',['ParamSelLooGPRegr',['../da/d9c/classgurls_1_1_param_sel_loo_g_p_regr.html',1,'gurls']]],
  ['paramselsiglam',['ParamSelSiglam',['../d6/d3a/classgurls_1_1_param_sel_siglam.html',1,'gurls']]],
  ['paramselsiglamho',['ParamSelSiglamHo',['../dc/de3/classgurls_1_1_param_sel_siglam_ho.html',1,'gurls']]],
  ['paramselsiglamhogpregr',['ParamSelSiglamHoGPRegr',['../d1/de1/classgurls_1_1_param_sel_siglam_ho_g_p_regr.html',1,'gurls']]],
  ['paramselsiglamloogpregr',['ParamSelSiglamLooGPRegr',['../d0/d75/classgurls_1_1_param_sel_siglam_loo_g_p_regr.html',1,'gurls']]],
  ['pdist',['pdist',['../db/d4e/namespacegurls.html#aae1b80d6308d315bae49f7e8e5c00fd4',1,'gurls']]],
  ['perfmacroavg',['PerfMacroAvg',['../d8/dc8/classgurls_1_1_perf_macro_avg.html',1,'gurls']]],
  ['performance',['Performance',['../d5/dac/classgurls_1_1_performance.html',1,'gurls']]],
  ['perfprecrec',['PerfPrecRec',['../d6/dbc/classgurls_1_1_perf_prec_rec.html',1,'gurls']]],
  ['perfrmse',['PerfRmse',['../d8/dc3/classgurls_1_1_perf_rmse.html',1,'gurls']]],
  ['pinv',['pinv',['../db/d4e/namespacegurls.html#a753b9fab2b7733245db71f4d59bcfc9b',1,'gurls::pinv(const gMat2D&lt; T &gt; &amp;A, gMat2D&lt; T &gt; &amp;Ainv, T RCOND=0)'],['../db/d4e/namespacegurls.html#adfc28aaab9ad9111e413da721438370a',1,'gurls::pinv(const T *A, const int rows, const int cols, int &amp;res_rows, int &amp;res_cols, T *RCOND=NULL)'],['../db/d4e/namespacegurls.html#a462f86faf9d2c90f8871ae7e223eb432',1,'gurls::pinv(const gMat2D&lt; float &gt; &amp;A, gMat2D&lt; float &gt; &amp;Ainv, float RCOND)']]],
  ['potrf_5f',['potrf_',['../db/d4e/namespacegurls.html#a8da7753eb788f84ac8474d39996f541f',1,'gurls::potrf_(char *UPLO, int *n, T *a, int *lda, int *info)'],['../db/d4e/namespacegurls.html#a39dee0a0ece0c39fa94fc01725eccb9a',1,'gurls::potrf_(char *UPLO, int *n, float *a, int *lda, int *info)'],['../db/d4e/namespacegurls.html#a2dd619a2e30c7d5039bd1312395bf361',1,'gurls::potrf_(char *UPLO, int *n, double *a, int *lda, int *info)']]],
  ['precrec_5fdriver',['precrec_driver',['../db/d4e/namespacegurls.html#acb4047b769eb39affe91e125f8ecb6df',1,'gurls::precrec_driver(const T *out, const T *gt, const unsigned long N, T *work)'],['../db/d4e/namespacegurls.html#af8659cac31df668780f9e9b022262526',1,'gurls::precrec_driver(const T *out, const T *gt, const unsigned long N)']]],
  ['preddual',['PredDual',['../d7/dcd/classgurls_1_1_pred_dual.html',1,'gurls']]],
  ['predgpregr',['PredGPRegr',['../da/d9e/classgurls_1_1_pred_g_p_regr.html',1,'gurls']]],
  ['prediction',['Prediction',['../d7/d57/classgurls_1_1_prediction.html',1,'gurls']]],
  ['predkernel',['PredKernel',['../d1/d99/classgurls_1_1_pred_kernel.html',1,'gurls']]],
  ['predkerneltraintest',['PredKernelTrainTest',['../d3/dd7/classgurls_1_1_pred_kernel_train_test.html',1,'gurls']]],
  ['predprimal',['PredPrimal',['../d8/d06/classgurls_1_1_pred_primal.html',1,'gurls']]],
  ['printall',['printAll',['../dc/d34/classgurls_1_1_gurls_options_list.html#a7464fb753696da7cb6637f1bfa719f20',1,'gurls::GurlsOptionsList']]],
  ['probtype',['probType',['../d5/d55/classgurls_1_1_gurls_wrapper.html#af7b202e0de7f9ddea8a7bfdd6e9ac8cb',1,'gurls::GurlsWrapper']]],
  ['push_5fback',['push_back',['../da/d90/classgurls_1_1_opt_array.html#a8d6dabe2d456204db6967e14aacf0f22',1,'gurls::OptArray']]]
];
